PROGRAM main
  USE ISO_C_BINDING
  USE ISO_FORTRAN_ENV
  INTEGER(INT64), PARAMETER :: NX=20!0!0!00
  INTEGER(INT64), PARAMETER :: NY=20!0!0!00
  INTEGER(INT64), PARAMETER :: ITERS=100000000_INT64
  INTEGER(INT64), DIMENSION(:,:), ALLOCATABLE :: A
  INTEGER(INT64) :: B,i
  INTEGER :: start, end, count_rate
  ALLOCATE(A(NX,NY))
  A = 1
  B = 0

  CALL SYSTEM_CLOCK(start,count_rate)
  DO i=1,ITERS
    B=B+ SUM(A*2)
  END DO
  CALL SYSTEM_CLOCK(end)
  PRINT *, "Time for main loop is " , REAL(end-start)/REAL(count_rate) , " seconds"
  PRINT *, "B = " , B 
END PROGRAM
